server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: PRODUCT-SERVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/api/v1/products/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/v1/orders/**
      - id: CART-SERVICE
        uri: lb://CART-SERVICE
        predicates:
        - Path=/api/v1/cart/**
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/api/v1/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost